apiVersion: apps/v1
kind: Deployment
metadata:
  name: caffy-beans-example
  labels:
    app: caffy-beans-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caffy-beans-example
  template:
    metadata:
      labels:
        app: caffy-beans-example
    spec:
      containers:
        - name: caffy-beans-example
          image: caffy-beans-example
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: caffy-beans-example
spec:
  selector:
    app: caffy-beans-example
  ports:
    - name: caffy-beans-example
      protocol: TCP
      port: 80
      targetPort: 8080